// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adb_config_demo.proto

package com.erobbing.adb_config_demo;

public final class AdbConfigDemo {
  private AdbConfigDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.erobbing.adb_config_demo.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>COMMON_ERROR = 1;</code>
     */
    COMMON_ERROR(1),
    /**
     * <code>UNKNOWN_CMD = 100;</code>
     */
    UNKNOWN_CMD(100),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>COMMON_ERROR = 1;</code>
     */
    public static final int COMMON_ERROR_VALUE = 1;
    /**
     * <code>UNKNOWN_CMD = 100;</code>
     */
    public static final int UNKNOWN_CMD_VALUE = 100;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return COMMON_ERROR;
        case 100: return UNKNOWN_CMD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.erobbing.adb_config_demo.AdbConfigDemo.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.erobbing.adb_config_demo.ErrorCode)
  }

  /**
   * Protobuf enum {@code com.erobbing.adb_config_demo.Cmd}
   */
  public enum Cmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>cmd_dummy = 0;</code>
     */
    cmd_dummy(0),
    /**
     * <pre>
     * 从设备端获取设置
     * </pre>
     *
     * <code>cmdReadConfig = 1;</code>
     */
    cmdReadConfig(1),
    /**
     * <pre>
     * 保存设置到设备端
     * </pre>
     *
     * <code>cmdWriteConfig = 2;</code>
     */
    cmdWriteConfig(2),
    /**
     * <pre>
     * 箱注册
     * </pre>
     *
     * <code>cmdRegisterBox = 3;</code>
     */
    cmdRegisterBox(3),
    /**
     * <pre>
     * 箱注销
     * </pre>
     *
     * <code>cmdUnregisterBox = 4;</code>
     */
    cmdUnregisterBox(4),
    /**
     * <pre>
     * 扣注销
     * </pre>
     *
     * <code>cmdUnregisterKey = 5;</code>
     */
    cmdUnregisterKey(5),
    /**
     * <pre>
     *清除鉴权码
     * </pre>
     *
     * <code>cmdClearAuthCode = 6;</code>
     */
    cmdClearAuthCode(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>cmd_dummy = 0;</code>
     */
    public static final int cmd_dummy_VALUE = 0;
    /**
     * <pre>
     * 从设备端获取设置
     * </pre>
     *
     * <code>cmdReadConfig = 1;</code>
     */
    public static final int cmdReadConfig_VALUE = 1;
    /**
     * <pre>
     * 保存设置到设备端
     * </pre>
     *
     * <code>cmdWriteConfig = 2;</code>
     */
    public static final int cmdWriteConfig_VALUE = 2;
    /**
     * <pre>
     * 箱注册
     * </pre>
     *
     * <code>cmdRegisterBox = 3;</code>
     */
    public static final int cmdRegisterBox_VALUE = 3;
    /**
     * <pre>
     * 箱注销
     * </pre>
     *
     * <code>cmdUnregisterBox = 4;</code>
     */
    public static final int cmdUnregisterBox_VALUE = 4;
    /**
     * <pre>
     * 扣注销
     * </pre>
     *
     * <code>cmdUnregisterKey = 5;</code>
     */
    public static final int cmdUnregisterKey_VALUE = 5;
    /**
     * <pre>
     *清除鉴权码
     * </pre>
     *
     * <code>cmdClearAuthCode = 6;</code>
     */
    public static final int cmdClearAuthCode_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Cmd valueOf(int value) {
      return forNumber(value);
    }

    public static Cmd forNumber(int value) {
      switch (value) {
        case 0: return cmd_dummy;
        case 1: return cmdReadConfig;
        case 2: return cmdWriteConfig;
        case 3: return cmdRegisterBox;
        case 4: return cmdUnregisterBox;
        case 5: return cmdUnregisterKey;
        case 6: return cmdClearAuthCode;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Cmd> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cmd>() {
            public Cmd findValueByNumber(int number) {
              return Cmd.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.erobbing.adb_config_demo.AdbConfigDemo.getDescriptor().getEnumTypes().get(1);
    }

    private static final Cmd[] VALUES = values();

    public static Cmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Cmd(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.erobbing.adb_config_demo.Cmd)
  }

  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.erobbing.adb_config_demo.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 0: OK; 其他值：错误码
     * </pre>
     *
     * <code>optional int32 errorCode = 1;</code>
     */
    int getErrorCode();

    /**
     * <pre>
     * 箱ID
     * </pre>
     *
     * <code>optional string boxID = 2;</code>
     */
    java.lang.String getBoxID();
    /**
     * <pre>
     * 箱ID
     * </pre>
     *
     * <code>optional string boxID = 2;</code>
     */
    com.google.protobuf.ByteString
        getBoxIDBytes();

    /**
     * <pre>
     * 钥匙扣ID
     * </pre>
     *
     * <code>optional string keyID = 3;</code>
     */
    java.lang.String getKeyID();
    /**
     * <pre>
     * 钥匙扣ID
     * </pre>
     *
     * <code>optional string keyID = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeyIDBytes();

    /**
     * <pre>
     * 店ID
     * </pre>
     *
     * <code>optional string shopID = 4;</code>
     */
    java.lang.String getShopID();
    /**
     * <pre>
     * 店ID
     * </pre>
     *
     * <code>optional string shopID = 4;</code>
     */
    com.google.protobuf.ByteString
        getShopIDBytes();

    /**
     * <pre>
     * 箱是否注册
     * </pre>
     *
     * <code>optional bool boxRegisted = 5;</code>
     */
    boolean getBoxRegisted();

    /**
     * <pre>
     * 省
     * </pre>
     *
     * <code>optional string provinceID = 6;</code>
     */
    java.lang.String getProvinceID();
    /**
     * <pre>
     * 省
     * </pre>
     *
     * <code>optional string provinceID = 6;</code>
     */
    com.google.protobuf.ByteString
        getProvinceIDBytes();

    /**
     * <pre>
     * 市
     * </pre>
     *
     * <code>optional string cityID = 7;</code>
     */
    java.lang.String getCityID();
    /**
     * <pre>
     * 市
     * </pre>
     *
     * <code>optional string cityID = 7;</code>
     */
    com.google.protobuf.ByteString
        getCityIDBytes();

    /**
     * <pre>
     * 制造商
     * </pre>
     *
     * <code>optional string manufacturerID = 8;</code>
     */
    java.lang.String getManufacturerID();
    /**
     * <pre>
     * 制造商
     * </pre>
     *
     * <code>optional string manufacturerID = 8;</code>
     */
    com.google.protobuf.ByteString
        getManufacturerIDBytes();

    /**
     * <code>optional string ip = 9;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 9;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional string ipmask = 10;</code>
     */
    java.lang.String getIpmask();
    /**
     * <code>optional string ipmask = 10;</code>
     */
    com.google.protobuf.ByteString
        getIpmaskBytes();

    /**
     * <code>optional string dns1 = 11;</code>
     */
    java.lang.String getDns1();
    /**
     * <code>optional string dns1 = 11;</code>
     */
    com.google.protobuf.ByteString
        getDns1Bytes();

    /**
     * <code>optional string dns2 = 12;</code>
     */
    java.lang.String getDns2();
    /**
     * <code>optional string dns2 = 12;</code>
     */
    com.google.protobuf.ByteString
        getDns2Bytes();

    /**
     * <code>optional string gateway = 13;</code>
     */
    java.lang.String getGateway();
    /**
     * <code>optional string gateway = 13;</code>
     */
    com.google.protobuf.ByteString
        getGatewayBytes();

    /**
     * <code>optional bool ipDhcp = 14;</code>
     */
    boolean getIpDhcp();

    /**
     * <pre>
     * [0..9] true: 钥匙已注册，false: 钥匙未注册
     * </pre>
     *
     * <code>repeated bool keyStatus = 15;</code>
     */
    java.util.List<java.lang.Boolean> getKeyStatusList();
    /**
     * <pre>
     * [0..9] true: 钥匙已注册，false: 钥匙未注册
     * </pre>
     *
     * <code>repeated bool keyStatus = 15;</code>
     */
    int getKeyStatusCount();
    /**
     * <pre>
     * [0..9] true: 钥匙已注册，false: 钥匙未注册
     * </pre>
     *
     * <code>repeated bool keyStatus = 15;</code>
     */
    boolean getKeyStatus(int index);

    /**
     * <pre>
     * 要操作的钥匙扣号 [1..10]
     * </pre>
     *
     * <code>optional int32 keyno = 16;</code>
     */
    int getKeyno();

    /**
     * <code>optional string wifiName = 17;</code>
     */
    java.lang.String getWifiName();
    /**
     * <code>optional string wifiName = 17;</code>
     */
    com.google.protobuf.ByteString
        getWifiNameBytes();

    /**
     * <code>optional string wifiPass = 18;</code>
     */
    java.lang.String getWifiPass();
    /**
     * <code>optional string wifiPass = 18;</code>
     */
    com.google.protobuf.ByteString
        getWifiPassBytes();
  }
  /**
   * <pre>
   * 每个通讯的数据内容，根据需要获取或设置某(几)个参数值
   * </pre>
   *
   * Protobuf type {@code com.erobbing.adb_config_demo.Config}
   */
  public  static final class Config extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.erobbing.adb_config_demo.Config)
      ConfigOrBuilder {
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Config() {
      errorCode_ = 0;
      boxID_ = "";
      keyID_ = "";
      shopID_ = "";
      boxRegisted_ = false;
      provinceID_ = "";
      cityID_ = "";
      manufacturerID_ = "";
      ip_ = "";
      ipmask_ = "";
      dns1_ = "";
      dns2_ = "";
      gateway_ = "";
      ipDhcp_ = false;
      keyStatus_ = java.util.Collections.emptyList();
      keyno_ = 0;
      wifiName_ = "";
      wifiPass_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              boxID_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              keyID_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              shopID_ = s;
              break;
            }
            case 40: {

              boxRegisted_ = input.readBool();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              provinceID_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              cityID_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              manufacturerID_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              ipmask_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              dns1_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              dns2_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              gateway_ = s;
              break;
            }
            case 112: {

              ipDhcp_ = input.readBool();
              break;
            }
            case 120: {
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
                keyStatus_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00004000;
              }
              keyStatus_.add(input.readBool());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00004000) == 0x00004000) && input.getBytesUntilLimit() > 0) {
                keyStatus_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00004000;
              }
              while (input.getBytesUntilLimit() > 0) {
                keyStatus_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            case 128: {

              keyno_ = input.readInt32();
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              wifiName_ = s;
              break;
            }
            case 146: {
              java.lang.String s = input.readStringRequireUtf8();

              wifiPass_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
          keyStatus_ = java.util.Collections.unmodifiableList(keyStatus_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.erobbing.adb_config_demo.AdbConfigDemo.Config.class, com.erobbing.adb_config_demo.AdbConfigDemo.Config.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <pre>
     * 0: OK; 其他值：错误码
     * </pre>
     *
     * <code>optional int32 errorCode = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int BOXID_FIELD_NUMBER = 2;
    private volatile java.lang.Object boxID_;
    /**
     * <pre>
     * 箱ID
     * </pre>
     *
     * <code>optional string boxID = 2;</code>
     */
    public java.lang.String getBoxID() {
      java.lang.Object ref = boxID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        boxID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 箱ID
     * </pre>
     *
     * <code>optional string boxID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBoxIDBytes() {
      java.lang.Object ref = boxID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boxID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEYID_FIELD_NUMBER = 3;
    private volatile java.lang.Object keyID_;
    /**
     * <pre>
     * 钥匙扣ID
     * </pre>
     *
     * <code>optional string keyID = 3;</code>
     */
    public java.lang.String getKeyID() {
      java.lang.Object ref = keyID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 钥匙扣ID
     * </pre>
     *
     * <code>optional string keyID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeyIDBytes() {
      java.lang.Object ref = keyID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHOPID_FIELD_NUMBER = 4;
    private volatile java.lang.Object shopID_;
    /**
     * <pre>
     * 店ID
     * </pre>
     *
     * <code>optional string shopID = 4;</code>
     */
    public java.lang.String getShopID() {
      java.lang.Object ref = shopID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shopID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 店ID
     * </pre>
     *
     * <code>optional string shopID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getShopIDBytes() {
      java.lang.Object ref = shopID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shopID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOXREGISTED_FIELD_NUMBER = 5;
    private boolean boxRegisted_;
    /**
     * <pre>
     * 箱是否注册
     * </pre>
     *
     * <code>optional bool boxRegisted = 5;</code>
     */
    public boolean getBoxRegisted() {
      return boxRegisted_;
    }

    public static final int PROVINCEID_FIELD_NUMBER = 6;
    private volatile java.lang.Object provinceID_;
    /**
     * <pre>
     * 省
     * </pre>
     *
     * <code>optional string provinceID = 6;</code>
     */
    public java.lang.String getProvinceID() {
      java.lang.Object ref = provinceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        provinceID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 省
     * </pre>
     *
     * <code>optional string provinceID = 6;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceIDBytes() {
      java.lang.Object ref = provinceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provinceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITYID_FIELD_NUMBER = 7;
    private volatile java.lang.Object cityID_;
    /**
     * <pre>
     * 市
     * </pre>
     *
     * <code>optional string cityID = 7;</code>
     */
    public java.lang.String getCityID() {
      java.lang.Object ref = cityID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cityID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 市
     * </pre>
     *
     * <code>optional string cityID = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCityIDBytes() {
      java.lang.Object ref = cityID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cityID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MANUFACTURERID_FIELD_NUMBER = 8;
    private volatile java.lang.Object manufacturerID_;
    /**
     * <pre>
     * 制造商
     * </pre>
     *
     * <code>optional string manufacturerID = 8;</code>
     */
    public java.lang.String getManufacturerID() {
      java.lang.Object ref = manufacturerID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturerID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 制造商
     * </pre>
     *
     * <code>optional string manufacturerID = 8;</code>
     */
    public com.google.protobuf.ByteString
        getManufacturerIDBytes() {
      java.lang.Object ref = manufacturerID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturerID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 9;
    private volatile java.lang.Object ip_;
    /**
     * <code>optional string ip = 9;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 9;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IPMASK_FIELD_NUMBER = 10;
    private volatile java.lang.Object ipmask_;
    /**
     * <code>optional string ipmask = 10;</code>
     */
    public java.lang.String getIpmask() {
      java.lang.Object ref = ipmask_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipmask_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ipmask = 10;</code>
     */
    public com.google.protobuf.ByteString
        getIpmaskBytes() {
      java.lang.Object ref = ipmask_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipmask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DNS1_FIELD_NUMBER = 11;
    private volatile java.lang.Object dns1_;
    /**
     * <code>optional string dns1 = 11;</code>
     */
    public java.lang.String getDns1() {
      java.lang.Object ref = dns1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dns1_ = s;
        return s;
      }
    }
    /**
     * <code>optional string dns1 = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDns1Bytes() {
      java.lang.Object ref = dns1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dns1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DNS2_FIELD_NUMBER = 12;
    private volatile java.lang.Object dns2_;
    /**
     * <code>optional string dns2 = 12;</code>
     */
    public java.lang.String getDns2() {
      java.lang.Object ref = dns2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dns2_ = s;
        return s;
      }
    }
    /**
     * <code>optional string dns2 = 12;</code>
     */
    public com.google.protobuf.ByteString
        getDns2Bytes() {
      java.lang.Object ref = dns2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dns2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GATEWAY_FIELD_NUMBER = 13;
    private volatile java.lang.Object gateway_;
    /**
     * <code>optional string gateway = 13;</code>
     */
    public java.lang.String getGateway() {
      java.lang.Object ref = gateway_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gateway_ = s;
        return s;
      }
    }
    /**
     * <code>optional string gateway = 13;</code>
     */
    public com.google.protobuf.ByteString
        getGatewayBytes() {
      java.lang.Object ref = gateway_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gateway_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IPDHCP_FIELD_NUMBER = 14;
    private boolean ipDhcp_;
    /**
     * <code>optional bool ipDhcp = 14;</code>
     */
    public boolean getIpDhcp() {
      return ipDhcp_;
    }

    public static final int KEYSTATUS_FIELD_NUMBER = 15;
    private java.util.List<java.lang.Boolean> keyStatus_;
    /**
     * <pre>
     * [0..9] true: 钥匙已注册，false: 钥匙未注册
     * </pre>
     *
     * <code>repeated bool keyStatus = 15;</code>
     */
    public java.util.List<java.lang.Boolean>
        getKeyStatusList() {
      return keyStatus_;
    }
    /**
     * <pre>
     * [0..9] true: 钥匙已注册，false: 钥匙未注册
     * </pre>
     *
     * <code>repeated bool keyStatus = 15;</code>
     */
    public int getKeyStatusCount() {
      return keyStatus_.size();
    }
    /**
     * <pre>
     * [0..9] true: 钥匙已注册，false: 钥匙未注册
     * </pre>
     *
     * <code>repeated bool keyStatus = 15;</code>
     */
    public boolean getKeyStatus(int index) {
      return keyStatus_.get(index);
    }
    private int keyStatusMemoizedSerializedSize = -1;

    public static final int KEYNO_FIELD_NUMBER = 16;
    private int keyno_;
    /**
     * <pre>
     * 要操作的钥匙扣号 [1..10]
     * </pre>
     *
     * <code>optional int32 keyno = 16;</code>
     */
    public int getKeyno() {
      return keyno_;
    }

    public static final int WIFINAME_FIELD_NUMBER = 17;
    private volatile java.lang.Object wifiName_;
    /**
     * <code>optional string wifiName = 17;</code>
     */
    public java.lang.String getWifiName() {
      java.lang.Object ref = wifiName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wifiName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string wifiName = 17;</code>
     */
    public com.google.protobuf.ByteString
        getWifiNameBytes() {
      java.lang.Object ref = wifiName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wifiName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WIFIPASS_FIELD_NUMBER = 18;
    private volatile java.lang.Object wifiPass_;
    /**
     * <code>optional string wifiPass = 18;</code>
     */
    public java.lang.String getWifiPass() {
      java.lang.Object ref = wifiPass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wifiPass_ = s;
        return s;
      }
    }
    /**
     * <code>optional string wifiPass = 18;</code>
     */
    public com.google.protobuf.ByteString
        getWifiPassBytes() {
      java.lang.Object ref = wifiPass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wifiPass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      if (!getBoxIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, boxID_);
      }
      if (!getKeyIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, keyID_);
      }
      if (!getShopIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, shopID_);
      }
      if (boxRegisted_ != false) {
        output.writeBool(5, boxRegisted_);
      }
      if (!getProvinceIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, provinceID_);
      }
      if (!getCityIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, cityID_);
      }
      if (!getManufacturerIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, manufacturerID_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ip_);
      }
      if (!getIpmaskBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, ipmask_);
      }
      if (!getDns1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, dns1_);
      }
      if (!getDns2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, dns2_);
      }
      if (!getGatewayBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, gateway_);
      }
      if (ipDhcp_ != false) {
        output.writeBool(14, ipDhcp_);
      }
      if (getKeyStatusList().size() > 0) {
        output.writeUInt32NoTag(122);
        output.writeUInt32NoTag(keyStatusMemoizedSerializedSize);
      }
      for (int i = 0; i < keyStatus_.size(); i++) {
        output.writeBoolNoTag(keyStatus_.get(i));
      }
      if (keyno_ != 0) {
        output.writeInt32(16, keyno_);
      }
      if (!getWifiNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, wifiName_);
      }
      if (!getWifiPassBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, wifiPass_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      if (!getBoxIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, boxID_);
      }
      if (!getKeyIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, keyID_);
      }
      if (!getShopIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, shopID_);
      }
      if (boxRegisted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, boxRegisted_);
      }
      if (!getProvinceIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, provinceID_);
      }
      if (!getCityIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, cityID_);
      }
      if (!getManufacturerIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, manufacturerID_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ip_);
      }
      if (!getIpmaskBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, ipmask_);
      }
      if (!getDns1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, dns1_);
      }
      if (!getDns2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, dns2_);
      }
      if (!getGatewayBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, gateway_);
      }
      if (ipDhcp_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, ipDhcp_);
      }
      {
        int dataSize = 0;
        dataSize = 1 * getKeyStatusList().size();
        size += dataSize;
        if (!getKeyStatusList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        keyStatusMemoizedSerializedSize = dataSize;
      }
      if (keyno_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, keyno_);
      }
      if (!getWifiNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, wifiName_);
      }
      if (!getWifiPassBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, wifiPass_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.erobbing.adb_config_demo.AdbConfigDemo.Config)) {
        return super.equals(obj);
      }
      com.erobbing.adb_config_demo.AdbConfigDemo.Config other = (com.erobbing.adb_config_demo.AdbConfigDemo.Config) obj;

      boolean result = true;
      result = result && (getErrorCode()
          == other.getErrorCode());
      result = result && getBoxID()
          .equals(other.getBoxID());
      result = result && getKeyID()
          .equals(other.getKeyID());
      result = result && getShopID()
          .equals(other.getShopID());
      result = result && (getBoxRegisted()
          == other.getBoxRegisted());
      result = result && getProvinceID()
          .equals(other.getProvinceID());
      result = result && getCityID()
          .equals(other.getCityID());
      result = result && getManufacturerID()
          .equals(other.getManufacturerID());
      result = result && getIp()
          .equals(other.getIp());
      result = result && getIpmask()
          .equals(other.getIpmask());
      result = result && getDns1()
          .equals(other.getDns1());
      result = result && getDns2()
          .equals(other.getDns2());
      result = result && getGateway()
          .equals(other.getGateway());
      result = result && (getIpDhcp()
          == other.getIpDhcp());
      result = result && getKeyStatusList()
          .equals(other.getKeyStatusList());
      result = result && (getKeyno()
          == other.getKeyno());
      result = result && getWifiName()
          .equals(other.getWifiName());
      result = result && getWifiPass()
          .equals(other.getWifiPass());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (37 * hash) + BOXID_FIELD_NUMBER;
      hash = (53 * hash) + getBoxID().hashCode();
      hash = (37 * hash) + KEYID_FIELD_NUMBER;
      hash = (53 * hash) + getKeyID().hashCode();
      hash = (37 * hash) + SHOPID_FIELD_NUMBER;
      hash = (53 * hash) + getShopID().hashCode();
      hash = (37 * hash) + BOXREGISTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBoxRegisted());
      hash = (37 * hash) + PROVINCEID_FIELD_NUMBER;
      hash = (53 * hash) + getProvinceID().hashCode();
      hash = (37 * hash) + CITYID_FIELD_NUMBER;
      hash = (53 * hash) + getCityID().hashCode();
      hash = (37 * hash) + MANUFACTURERID_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturerID().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + IPMASK_FIELD_NUMBER;
      hash = (53 * hash) + getIpmask().hashCode();
      hash = (37 * hash) + DNS1_FIELD_NUMBER;
      hash = (53 * hash) + getDns1().hashCode();
      hash = (37 * hash) + DNS2_FIELD_NUMBER;
      hash = (53 * hash) + getDns2().hashCode();
      hash = (37 * hash) + GATEWAY_FIELD_NUMBER;
      hash = (53 * hash) + getGateway().hashCode();
      hash = (37 * hash) + IPDHCP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIpDhcp());
      if (getKeyStatusCount() > 0) {
        hash = (37 * hash) + KEYSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getKeyStatusList().hashCode();
      }
      hash = (37 * hash) + KEYNO_FIELD_NUMBER;
      hash = (53 * hash) + getKeyno();
      hash = (37 * hash) + WIFINAME_FIELD_NUMBER;
      hash = (53 * hash) + getWifiName().hashCode();
      hash = (37 * hash) + WIFIPASS_FIELD_NUMBER;
      hash = (53 * hash) + getWifiPass().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.erobbing.adb_config_demo.AdbConfigDemo.Config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 每个通讯的数据内容，根据需要获取或设置某(几)个参数值
     * </pre>
     *
     * Protobuf type {@code com.erobbing.adb_config_demo.Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.erobbing.adb_config_demo.Config)
        com.erobbing.adb_config_demo.AdbConfigDemo.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.erobbing.adb_config_demo.AdbConfigDemo.Config.class, com.erobbing.adb_config_demo.AdbConfigDemo.Config.Builder.class);
      }

      // Construct using com.erobbing.adb_config_demo.AdbConfigDemo.Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        boxID_ = "";

        keyID_ = "";

        shopID_ = "";

        boxRegisted_ = false;

        provinceID_ = "";

        cityID_ = "";

        manufacturerID_ = "";

        ip_ = "";

        ipmask_ = "";

        dns1_ = "";

        dns2_ = "";

        gateway_ = "";

        ipDhcp_ = false;

        keyStatus_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        keyno_ = 0;

        wifiName_ = "";

        wifiPass_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.erobbing.adb_config_demo.AdbConfigDemo.internal_static_com_erobbing_adb_config_demo_Config_descriptor;
      }

      public com.erobbing.adb_config_demo.AdbConfigDemo.Config getDefaultInstanceForType() {
        return com.erobbing.adb_config_demo.AdbConfigDemo.Config.getDefaultInstance();
      }

      public com.erobbing.adb_config_demo.AdbConfigDemo.Config build() {
        com.erobbing.adb_config_demo.AdbConfigDemo.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.erobbing.adb_config_demo.AdbConfigDemo.Config buildPartial() {
        com.erobbing.adb_config_demo.AdbConfigDemo.Config result = new com.erobbing.adb_config_demo.AdbConfigDemo.Config(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.errorCode_ = errorCode_;
        result.boxID_ = boxID_;
        result.keyID_ = keyID_;
        result.shopID_ = shopID_;
        result.boxRegisted_ = boxRegisted_;
        result.provinceID_ = provinceID_;
        result.cityID_ = cityID_;
        result.manufacturerID_ = manufacturerID_;
        result.ip_ = ip_;
        result.ipmask_ = ipmask_;
        result.dns1_ = dns1_;
        result.dns2_ = dns2_;
        result.gateway_ = gateway_;
        result.ipDhcp_ = ipDhcp_;
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          keyStatus_ = java.util.Collections.unmodifiableList(keyStatus_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.keyStatus_ = keyStatus_;
        result.keyno_ = keyno_;
        result.wifiName_ = wifiName_;
        result.wifiPass_ = wifiPass_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.erobbing.adb_config_demo.AdbConfigDemo.Config) {
          return mergeFrom((com.erobbing.adb_config_demo.AdbConfigDemo.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.erobbing.adb_config_demo.AdbConfigDemo.Config other) {
        if (other == com.erobbing.adb_config_demo.AdbConfigDemo.Config.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.getBoxID().isEmpty()) {
          boxID_ = other.boxID_;
          onChanged();
        }
        if (!other.getKeyID().isEmpty()) {
          keyID_ = other.keyID_;
          onChanged();
        }
        if (!other.getShopID().isEmpty()) {
          shopID_ = other.shopID_;
          onChanged();
        }
        if (other.getBoxRegisted() != false) {
          setBoxRegisted(other.getBoxRegisted());
        }
        if (!other.getProvinceID().isEmpty()) {
          provinceID_ = other.provinceID_;
          onChanged();
        }
        if (!other.getCityID().isEmpty()) {
          cityID_ = other.cityID_;
          onChanged();
        }
        if (!other.getManufacturerID().isEmpty()) {
          manufacturerID_ = other.manufacturerID_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getIpmask().isEmpty()) {
          ipmask_ = other.ipmask_;
          onChanged();
        }
        if (!other.getDns1().isEmpty()) {
          dns1_ = other.dns1_;
          onChanged();
        }
        if (!other.getDns2().isEmpty()) {
          dns2_ = other.dns2_;
          onChanged();
        }
        if (!other.getGateway().isEmpty()) {
          gateway_ = other.gateway_;
          onChanged();
        }
        if (other.getIpDhcp() != false) {
          setIpDhcp(other.getIpDhcp());
        }
        if (!other.keyStatus_.isEmpty()) {
          if (keyStatus_.isEmpty()) {
            keyStatus_ = other.keyStatus_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureKeyStatusIsMutable();
            keyStatus_.addAll(other.keyStatus_);
          }
          onChanged();
        }
        if (other.getKeyno() != 0) {
          setKeyno(other.getKeyno());
        }
        if (!other.getWifiName().isEmpty()) {
          wifiName_ = other.wifiName_;
          onChanged();
        }
        if (!other.getWifiPass().isEmpty()) {
          wifiPass_ = other.wifiPass_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.erobbing.adb_config_demo.AdbConfigDemo.Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.erobbing.adb_config_demo.AdbConfigDemo.Config) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errorCode_ ;
      /**
       * <pre>
       * 0: OK; 其他值：错误码
       * </pre>
       *
       * <code>optional int32 errorCode = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <pre>
       * 0: OK; 其他值：错误码
       * </pre>
       *
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0: OK; 其他值：错误码
       * </pre>
       *
       * <code>optional int32 errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object boxID_ = "";
      /**
       * <pre>
       * 箱ID
       * </pre>
       *
       * <code>optional string boxID = 2;</code>
       */
      public java.lang.String getBoxID() {
        java.lang.Object ref = boxID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          boxID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 箱ID
       * </pre>
       *
       * <code>optional string boxID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBoxIDBytes() {
        java.lang.Object ref = boxID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          boxID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 箱ID
       * </pre>
       *
       * <code>optional string boxID = 2;</code>
       */
      public Builder setBoxID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        boxID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 箱ID
       * </pre>
       *
       * <code>optional string boxID = 2;</code>
       */
      public Builder clearBoxID() {
        
        boxID_ = getDefaultInstance().getBoxID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 箱ID
       * </pre>
       *
       * <code>optional string boxID = 2;</code>
       */
      public Builder setBoxIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        boxID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object keyID_ = "";
      /**
       * <pre>
       * 钥匙扣ID
       * </pre>
       *
       * <code>optional string keyID = 3;</code>
       */
      public java.lang.String getKeyID() {
        java.lang.Object ref = keyID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 钥匙扣ID
       * </pre>
       *
       * <code>optional string keyID = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeyIDBytes() {
        java.lang.Object ref = keyID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 钥匙扣ID
       * </pre>
       *
       * <code>optional string keyID = 3;</code>
       */
      public Builder setKeyID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 钥匙扣ID
       * </pre>
       *
       * <code>optional string keyID = 3;</code>
       */
      public Builder clearKeyID() {
        
        keyID_ = getDefaultInstance().getKeyID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 钥匙扣ID
       * </pre>
       *
       * <code>optional string keyID = 3;</code>
       */
      public Builder setKeyIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keyID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shopID_ = "";
      /**
       * <pre>
       * 店ID
       * </pre>
       *
       * <code>optional string shopID = 4;</code>
       */
      public java.lang.String getShopID() {
        java.lang.Object ref = shopID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shopID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 店ID
       * </pre>
       *
       * <code>optional string shopID = 4;</code>
       */
      public com.google.protobuf.ByteString
          getShopIDBytes() {
        java.lang.Object ref = shopID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shopID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 店ID
       * </pre>
       *
       * <code>optional string shopID = 4;</code>
       */
      public Builder setShopID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shopID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 店ID
       * </pre>
       *
       * <code>optional string shopID = 4;</code>
       */
      public Builder clearShopID() {
        
        shopID_ = getDefaultInstance().getShopID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 店ID
       * </pre>
       *
       * <code>optional string shopID = 4;</code>
       */
      public Builder setShopIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shopID_ = value;
        onChanged();
        return this;
      }

      private boolean boxRegisted_ ;
      /**
       * <pre>
       * 箱是否注册
       * </pre>
       *
       * <code>optional bool boxRegisted = 5;</code>
       */
      public boolean getBoxRegisted() {
        return boxRegisted_;
      }
      /**
       * <pre>
       * 箱是否注册
       * </pre>
       *
       * <code>optional bool boxRegisted = 5;</code>
       */
      public Builder setBoxRegisted(boolean value) {
        
        boxRegisted_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 箱是否注册
       * </pre>
       *
       * <code>optional bool boxRegisted = 5;</code>
       */
      public Builder clearBoxRegisted() {
        
        boxRegisted_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object provinceID_ = "";
      /**
       * <pre>
       * 省
       * </pre>
       *
       * <code>optional string provinceID = 6;</code>
       */
      public java.lang.String getProvinceID() {
        java.lang.Object ref = provinceID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          provinceID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 省
       * </pre>
       *
       * <code>optional string provinceID = 6;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceIDBytes() {
        java.lang.Object ref = provinceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          provinceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 省
       * </pre>
       *
       * <code>optional string provinceID = 6;</code>
       */
      public Builder setProvinceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        provinceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 省
       * </pre>
       *
       * <code>optional string provinceID = 6;</code>
       */
      public Builder clearProvinceID() {
        
        provinceID_ = getDefaultInstance().getProvinceID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 省
       * </pre>
       *
       * <code>optional string provinceID = 6;</code>
       */
      public Builder setProvinceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        provinceID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cityID_ = "";
      /**
       * <pre>
       * 市
       * </pre>
       *
       * <code>optional string cityID = 7;</code>
       */
      public java.lang.String getCityID() {
        java.lang.Object ref = cityID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cityID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 市
       * </pre>
       *
       * <code>optional string cityID = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCityIDBytes() {
        java.lang.Object ref = cityID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cityID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 市
       * </pre>
       *
       * <code>optional string cityID = 7;</code>
       */
      public Builder setCityID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cityID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 市
       * </pre>
       *
       * <code>optional string cityID = 7;</code>
       */
      public Builder clearCityID() {
        
        cityID_ = getDefaultInstance().getCityID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 市
       * </pre>
       *
       * <code>optional string cityID = 7;</code>
       */
      public Builder setCityIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cityID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object manufacturerID_ = "";
      /**
       * <pre>
       * 制造商
       * </pre>
       *
       * <code>optional string manufacturerID = 8;</code>
       */
      public java.lang.String getManufacturerID() {
        java.lang.Object ref = manufacturerID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          manufacturerID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 制造商
       * </pre>
       *
       * <code>optional string manufacturerID = 8;</code>
       */
      public com.google.protobuf.ByteString
          getManufacturerIDBytes() {
        java.lang.Object ref = manufacturerID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manufacturerID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 制造商
       * </pre>
       *
       * <code>optional string manufacturerID = 8;</code>
       */
      public Builder setManufacturerID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        manufacturerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 制造商
       * </pre>
       *
       * <code>optional string manufacturerID = 8;</code>
       */
      public Builder clearManufacturerID() {
        
        manufacturerID_ = getDefaultInstance().getManufacturerID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 制造商
       * </pre>
       *
       * <code>optional string manufacturerID = 8;</code>
       */
      public Builder setManufacturerIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        manufacturerID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 9;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 9;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 9;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 9;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 9;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ipmask_ = "";
      /**
       * <code>optional string ipmask = 10;</code>
       */
      public java.lang.String getIpmask() {
        java.lang.Object ref = ipmask_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipmask_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ipmask = 10;</code>
       */
      public com.google.protobuf.ByteString
          getIpmaskBytes() {
        java.lang.Object ref = ipmask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipmask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ipmask = 10;</code>
       */
      public Builder setIpmask(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipmask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ipmask = 10;</code>
       */
      public Builder clearIpmask() {
        
        ipmask_ = getDefaultInstance().getIpmask();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ipmask = 10;</code>
       */
      public Builder setIpmaskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipmask_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dns1_ = "";
      /**
       * <code>optional string dns1 = 11;</code>
       */
      public java.lang.String getDns1() {
        java.lang.Object ref = dns1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dns1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dns1 = 11;</code>
       */
      public com.google.protobuf.ByteString
          getDns1Bytes() {
        java.lang.Object ref = dns1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dns1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dns1 = 11;</code>
       */
      public Builder setDns1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dns1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dns1 = 11;</code>
       */
      public Builder clearDns1() {
        
        dns1_ = getDefaultInstance().getDns1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dns1 = 11;</code>
       */
      public Builder setDns1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dns1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dns2_ = "";
      /**
       * <code>optional string dns2 = 12;</code>
       */
      public java.lang.String getDns2() {
        java.lang.Object ref = dns2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dns2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dns2 = 12;</code>
       */
      public com.google.protobuf.ByteString
          getDns2Bytes() {
        java.lang.Object ref = dns2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dns2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dns2 = 12;</code>
       */
      public Builder setDns2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dns2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dns2 = 12;</code>
       */
      public Builder clearDns2() {
        
        dns2_ = getDefaultInstance().getDns2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dns2 = 12;</code>
       */
      public Builder setDns2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dns2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gateway_ = "";
      /**
       * <code>optional string gateway = 13;</code>
       */
      public java.lang.String getGateway() {
        java.lang.Object ref = gateway_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gateway_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gateway = 13;</code>
       */
      public com.google.protobuf.ByteString
          getGatewayBytes() {
        java.lang.Object ref = gateway_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gateway_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gateway = 13;</code>
       */
      public Builder setGateway(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gateway_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gateway = 13;</code>
       */
      public Builder clearGateway() {
        
        gateway_ = getDefaultInstance().getGateway();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gateway = 13;</code>
       */
      public Builder setGatewayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gateway_ = value;
        onChanged();
        return this;
      }

      private boolean ipDhcp_ ;
      /**
       * <code>optional bool ipDhcp = 14;</code>
       */
      public boolean getIpDhcp() {
        return ipDhcp_;
      }
      /**
       * <code>optional bool ipDhcp = 14;</code>
       */
      public Builder setIpDhcp(boolean value) {
        
        ipDhcp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool ipDhcp = 14;</code>
       */
      public Builder clearIpDhcp() {
        
        ipDhcp_ = false;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Boolean> keyStatus_ = java.util.Collections.emptyList();
      private void ensureKeyStatusIsMutable() {
        if (!((bitField0_ & 0x00004000) == 0x00004000)) {
          keyStatus_ = new java.util.ArrayList<java.lang.Boolean>(keyStatus_);
          bitField0_ |= 0x00004000;
         }
      }
      /**
       * <pre>
       * [0..9] true: 钥匙已注册，false: 钥匙未注册
       * </pre>
       *
       * <code>repeated bool keyStatus = 15;</code>
       */
      public java.util.List<java.lang.Boolean>
          getKeyStatusList() {
        return java.util.Collections.unmodifiableList(keyStatus_);
      }
      /**
       * <pre>
       * [0..9] true: 钥匙已注册，false: 钥匙未注册
       * </pre>
       *
       * <code>repeated bool keyStatus = 15;</code>
       */
      public int getKeyStatusCount() {
        return keyStatus_.size();
      }
      /**
       * <pre>
       * [0..9] true: 钥匙已注册，false: 钥匙未注册
       * </pre>
       *
       * <code>repeated bool keyStatus = 15;</code>
       */
      public boolean getKeyStatus(int index) {
        return keyStatus_.get(index);
      }
      /**
       * <pre>
       * [0..9] true: 钥匙已注册，false: 钥匙未注册
       * </pre>
       *
       * <code>repeated bool keyStatus = 15;</code>
       */
      public Builder setKeyStatus(
          int index, boolean value) {
        ensureKeyStatusIsMutable();
        keyStatus_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * [0..9] true: 钥匙已注册，false: 钥匙未注册
       * </pre>
       *
       * <code>repeated bool keyStatus = 15;</code>
       */
      public Builder addKeyStatus(boolean value) {
        ensureKeyStatusIsMutable();
        keyStatus_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * [0..9] true: 钥匙已注册，false: 钥匙未注册
       * </pre>
       *
       * <code>repeated bool keyStatus = 15;</code>
       */
      public Builder addAllKeyStatus(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureKeyStatusIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keyStatus_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * [0..9] true: 钥匙已注册，false: 钥匙未注册
       * </pre>
       *
       * <code>repeated bool keyStatus = 15;</code>
       */
      public Builder clearKeyStatus() {
        keyStatus_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
        return this;
      }

      private int keyno_ ;
      /**
       * <pre>
       * 要操作的钥匙扣号 [1..10]
       * </pre>
       *
       * <code>optional int32 keyno = 16;</code>
       */
      public int getKeyno() {
        return keyno_;
      }
      /**
       * <pre>
       * 要操作的钥匙扣号 [1..10]
       * </pre>
       *
       * <code>optional int32 keyno = 16;</code>
       */
      public Builder setKeyno(int value) {
        
        keyno_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 要操作的钥匙扣号 [1..10]
       * </pre>
       *
       * <code>optional int32 keyno = 16;</code>
       */
      public Builder clearKeyno() {
        
        keyno_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object wifiName_ = "";
      /**
       * <code>optional string wifiName = 17;</code>
       */
      public java.lang.String getWifiName() {
        java.lang.Object ref = wifiName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wifiName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wifiName = 17;</code>
       */
      public com.google.protobuf.ByteString
          getWifiNameBytes() {
        java.lang.Object ref = wifiName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wifiName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wifiName = 17;</code>
       */
      public Builder setWifiName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wifiName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiName = 17;</code>
       */
      public Builder clearWifiName() {
        
        wifiName_ = getDefaultInstance().getWifiName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiName = 17;</code>
       */
      public Builder setWifiNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wifiName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object wifiPass_ = "";
      /**
       * <code>optional string wifiPass = 18;</code>
       */
      public java.lang.String getWifiPass() {
        java.lang.Object ref = wifiPass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wifiPass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wifiPass = 18;</code>
       */
      public com.google.protobuf.ByteString
          getWifiPassBytes() {
        java.lang.Object ref = wifiPass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wifiPass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wifiPass = 18;</code>
       */
      public Builder setWifiPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wifiPass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiPass = 18;</code>
       */
      public Builder clearWifiPass() {
        
        wifiPass_ = getDefaultInstance().getWifiPass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiPass = 18;</code>
       */
      public Builder setWifiPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wifiPass_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.erobbing.adb_config_demo.Config)
    }

    // @@protoc_insertion_point(class_scope:com.erobbing.adb_config_demo.Config)
    private static final com.erobbing.adb_config_demo.AdbConfigDemo.Config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.erobbing.adb_config_demo.AdbConfigDemo.Config();
    }

    public static com.erobbing.adb_config_demo.AdbConfigDemo.Config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Config>
        PARSER = new com.google.protobuf.AbstractParser<Config>() {
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Config(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    public com.erobbing.adb_config_demo.AdbConfigDemo.Config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_erobbing_adb_config_demo_Config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_erobbing_adb_config_demo_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025adb_config_demo.proto\022\034com.erobbing.ad" +
      "b_config_demo\"\271\002\n\006Config\022\021\n\terrorCode\030\001 " +
      "\001(\005\022\r\n\005boxID\030\002 \001(\t\022\r\n\005keyID\030\003 \001(\t\022\016\n\006sho" +
      "pID\030\004 \001(\t\022\023\n\013boxRegisted\030\005 \001(\010\022\022\n\nprovin" +
      "ceID\030\006 \001(\t\022\016\n\006cityID\030\007 \001(\t\022\026\n\016manufactur" +
      "erID\030\010 \001(\t\022\n\n\002ip\030\t \001(\t\022\016\n\006ipmask\030\n \001(\t\022\014" +
      "\n\004dns1\030\013 \001(\t\022\014\n\004dns2\030\014 \001(\t\022\017\n\007gateway\030\r " +
      "\001(\t\022\016\n\006ipDhcp\030\016 \001(\010\022\021\n\tkeyStatus\030\017 \003(\010\022\r" +
      "\n\005keyno\030\020 \001(\005\022\020\n\010wifiName\030\021 \001(\t\022\020\n\010wifiP" +
      "ass\030\022 \001(\t*6\n\tErrorCode\022\006\n\002OK\020\000\022\020\n\014COMMON",
      "_ERROR\020\001\022\017\n\013UNKNOWN_CMD\020d*\221\001\n\003Cmd\022\r\n\tcmd" +
      "_dummy\020\000\022\021\n\rcmdReadConfig\020\001\022\022\n\016cmdWriteC" +
      "onfig\020\002\022\022\n\016cmdRegisterBox\020\003\022\024\n\020cmdUnregi" +
      "sterBox\020\004\022\024\n\020cmdUnregisterKey\020\005\022\024\n\020cmdCl" +
      "earAuthCode\020\006b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_erobbing_adb_config_demo_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_erobbing_adb_config_demo_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_erobbing_adb_config_demo_Config_descriptor,
        new java.lang.String[] { "ErrorCode", "BoxID", "KeyID", "ShopID", "BoxRegisted", "ProvinceID", "CityID", "ManufacturerID", "Ip", "Ipmask", "Dns1", "Dns2", "Gateway", "IpDhcp", "KeyStatus", "Keyno", "WifiName", "WifiPass", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
